force-app/main/default/objects/Event_Place__c/Event_Place__c.object-meta.xml
<CustomObject>
    <label>Event Place</label>
    <nameField>
        <label>Event Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Place__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Event_Place__c.field-meta.xml
<CustomField>
    <fullName>Event_Place__c</fullName>
    <label>Event Place</label>
    <referenceTo>Event_Place__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Days_remains__c.field-meta.xml
<CustomField>
    <fullName>Days_remains__c</fullName>
    <formula>Session_Date__c  - DATETIMEVALUE(TODAY())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days remains</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FirstNamedCredentialsClass.cls
@RestResource (urlMapping='/kanunnikov/*')
global class FirstNamedCredentialsClass {
    public FirstNamedCredentialsClass() {

    }
    //workbench: /services/apexrest/kanunnikov
    @HttpGet
    global static void getSessionsOnWeek() {
        List<Session__c> s = [SELECT Id, Name 
                              FROM Session__c 
                              WHERE Days_remains__c >= 0 
                              AND Days_remains__c <= 7
                              FOR UPDATE];

        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(s));
        RestContext.response.statusCode = 200;
    }


    //workbench: /services/apexrest/kanunnikov?id=a097Q0000033II5QAM (use id from get method)
    @httpDelete
    global static void deleteSession(){
        Map<String,String> paramsMap = RestContext.request.params;
        String sessionId = paramsMap.get('id');
        Session__c s = [SELECT id FROM Session__c WHERE Id =:sessionId FOR UPDATE];
        delete s;
    }

    //workbench: /services/apexrest/kanunnikov 
    //JSON sample:
    //{
    //    "place": "restplace",
    //    "room": "restroom",
    //    "session": "restsession"
    //}
    @httpPost
    global static void createSession(){
        Map<String,String> paramsMap = RestContext.request.params;
        
        Event_Place__c placeRest = new Event_Place__c(Name = paramsMap.get('place'));
        insert placeRest;
        
        Room__c roomRest = new Room__c(Name = paramsMap.get('room'),
                                       Event_Place__c = placeRest.id);
        insert roomRest;

        Session__c sessionToInsert = new Session__C(Name = paramsMap.get('session'),
                                                    Room__c = roomRest.id); 
        insert sessionToInsert;       
    }

    //workbench: /services/apexrest/kanunnikov 
    //JSON sample (use id from get method):
    //{
    //    "id": "a097Q0000031qJOQAY",
    //    "description": "the most incredible session forever",
    //}
    @httpPut
    global static void changeSessionDescription(){
        Map<String,String> paramsMap = RestContext.request.params;
        String sId = paramsMap.get('id');
        Id sessionId = Id.valueOf(sId);
        String description = paramsMap.get('description');
        Session__c s = new Session__c(Id = sessionId, Description__c = description);
        update s;
    }
}