force-app/main/default/objects/Event_Place__c/Event_Place__c.object-meta.xml
<CustomObject>
    <label>Event Place</label>
    <nameField>
        <label>Event Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Place__c/fields/Number_of_related_sessions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_sessions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of related sessions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Place__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Event_Place__c.field-meta.xml
<CustomField>
    <fullName>Event_Place__c</fullName>
    <label>Event Place</label>
    <referenceTo>Event_Place__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_Place_counter_switch__c.field-meta.xml
<CustomField>
    <fullName>Event_Place_counter_switch__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Event Place counter switch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>Speaker-{0}</displayFormat>
        <label>Session Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Room</relationshipLabel>
    <relationshipName>Room</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionTriggerHandler.cls
public with sharing class SessionTriggerHandler {
    public SessionTriggerHandler() {

    }

    public static Boolean isScheduled = true;

    public static void archiveCheckerBeforeInsert (List<Session__c> newList){
        if (isDateInThePast(newList)) {
            for (Session__c s : newList) {
                if (s.name.contains('ARCHIVE')) {
                    s.isArchive__c = true;
                }
            }     
        }
    }

    public static void archiveCheckerBeforeUpdate (List<Session__c> newList, List<Session__c> oldList){
        if (isDateChanged(newList, oldList)) {
            for (Session__c s : newList) {
                if (s.name.contains('ARCHIVE')) {
                    s.isArchive__c = true;
                }
            }     
        }
    }

    @future
    public static void sessionNumUpdate (){
        if(!isScheduled){
            Map<Id,Decimal> oldValues = oldNumRelatedSes();
            Map<Id,Decimal> newValues = newNumRelatedSes();
            List<Event_Place__c> updateable = new List<Event_Place__c>();
            Set<Id> setone = oldValues.keySet();        
            for (Id key : setone) {
                if(oldValues.get(key) != newValues.get(key)){
                    updateable.add(new Event_Place__c (Id = key,  
                                                       Number_of_related_sessions__c = newValues.get(key)));
                }
            }
            if(!updateable.isEmpty()){
                update updateable;
            }
        }
    }

    public static void enqueueJobOnDateUpdate(List<Session__c> newList, List<Session__c> oldList){
        if(isDateChanged(newList, oldList)){
            ExternalObjectsHandler.cleanBeforeQueue();
            System.enqueueJob(new ExternalObjectsHandler());
        }
    }

    private static Boolean isDateInThePast (List<Session__c> newList){
        for(Session__c s : newList){
            if(s.Session_Date__c < DateTime.now()){
                return true;
            }
        }
        return false;
    }
    
    private static Boolean isDateChanged (List<Session__c> newList, List<Session__c> oldList){
        for(Session__c sn : newList){
            for (Session__c so : oldList) {
                if(sn.Session_Date__c != so.Session_Date__c){
                    return true;
                }
            }
        }
        return false;
    }

    private static Map<Id,Decimal> oldNumRelatedSes(){
        List<Event_Place__c> places = [SELECT Id, 
                                      Number_of_related_sessions__c 
                                      FROM Event_Place__c];
        Map<Id,Decimal> oldValues = new Map<Id,Decimal>();
            for (Event_Place__c p : places) {
                oldValues.put(p.Id, p.Number_of_related_sessions__c);
            }
        return oldValues;
    }

    private static Map<Id,Decimal> newNumRelatedSes(){
        List<AggregateResult> newResult = [SELECT Room__r.Event_Place__r.Id, 
                                           COUNT(Id) counter 
                                           FROM Session__c
                                           WHERE Session__c.Event_Place_counter_switch__c = true
                                           GROUP BY Room__r.Event_Place__r.Id];
        Map<Id,Decimal> newValues = new Map<Id,Decimal>();
            for (AggregateResult agr : newResult) {
                newValues.put((Id)agr.get('Id'), (Decimal)agr.get('counter'));
            }
        return newValues;
    }
}