force-app/main/default/objects/Event_Place__c/Event_Place__c.object-meta.xml
<CustomObject>
    <label>Event Place</label>
    <nameField>
        <label>Event Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Place__c/fields/Number_of_related_sessions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_sessions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of related sessions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Place__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/tests/SessionNumScheduledBatchTest.cls
@isTest
private class SessionNumScheduledBatchTest {
    
    @isTest
    private static void test() {
        //static resource session to meet the batch last modification date requirements
        Session__c[] sList = test.loadData(Session__c.sObjectType,'sfseLastModDateInPast');
        
        Test.startTest();
        Database.executeBatch(new SessionNumScheduledBatch());
        SessionNumScheduledBatch.fireOncePerDaySchedule();
        Test.stopTest();

        List<Event_Place__c> epList = [SELECT Id, Number_of_related_sessions__c 
                                       FROM Event_Place__c]; 
        //be aware of expected value
        Assert.areEqual(1, epList[0].Number_of_related_sessions__c, 'Incorrect number');  
    }
    


}