force-app/main/default/objects/Event_Place__c/Event_Place__c.object-meta.xml
<CustomObject>
    <label>Event Place</label>
    <nameField>
        <label>Event Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Event_Place__c.field-meta.xml
<CustomField>
    <fullName>Event_Place__c</fullName>
    <label>Event Place</label>
    <referenceTo>Event_Place__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/TestResponse.cls
@isTest
private class TestResponse {
    @isTest(SeeAllData=true)
    private static void testListConstructor(){
        List<Event_Place__c> epList = [SELECT (SELECT Id FROM Rooms__r) 
                                       FROM Event_Place__c 
                                       WHERE Id = 'a0B7Q00000265gVUAQ'];

        Set<Room__c> roomsId = new Set<Room__c>();
        for (Event_Place__c ep : epList) {
           for (Room__c r : ep.Rooms__r) {
                roomsId.add(r);            
           }
        }
        System.debug('roomsId -- ' + roomsId);

        List<Room__c> roomList = [SELECT Name FROM Room__c WHERE Id IN :roomsId];
        System.debug('roomList ' + roomList);

        QuickActionResponse resp = new QuickActionResponse(roomList);
    }
}