force-app/main/default/objects/Event_Place__c/Event_Place__c.object-meta.xml
<CustomObject>
    <label>Event Place</label>
    <nameField>
        <label>Event Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalObject__c/ExternalObject__c.object-meta.xml
<CustomObject>
    <label>ExternalObject</label>
    <nameField>
        <label>ExternalObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExternalObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalObject__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Event_Place__c.field-meta.xml
<CustomField>
    <fullName>Event_Place__c</fullName>
    <label>Event Place</label>
    <referenceTo>Event_Place__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>Speaker-{0}</displayFormat>
        <label>Session Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Room</relationshipLabel>
    <relationshipName>Room</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/SessionTriggerHandlerTest.cls
@isTest
private class SessionTriggerHandlerTest{

    @isTest
    private static void testArchiveCheckerInsert(){
        List<Session__c> newList = TestDataFactory.getNewSession(1);
        newList[0].Session_Date__c = Datetime.now().addDays(-3);
        newList[0].Name = 'ARCHIVE 1';
        newList[0].isArchive__c = false;

        Test.startTest();
        insert newList;
        Test.stopTest();

        List<Session__c> sList = [SELECT Id, isArchive__c FROM Session__c WHERE Id IN :newList];
        Boolean res = sList[0].isArchive__c;
        Assert.areEqual(true, res, 'Checkbox should be checked but it is not'); 
    }
    
    @isTest
    private static void testSessionNumUpdate(){
        List<Session__c> s = TestDataFactory.getNewSession(1);
        Test.startTest();
        Database.SaveResult[] dsr = Database.insert(s);
        Database.DeleteResult[] ddr = Database.delete(s);
        Test.stopTest();
        Assert.areEqual(dsr[0].isSuccess(), ddr[0].isSuccess(), 'DML exception');
    }
    
    @isTest
    private static void testGetIdOfLastModifiedPlaces(){
        Set<Id> idSet = TestDataFactory.getIdofFewPlaces(10);
        List<Session__c> s = [SELECT Id FROM Session__c WHERE Id IN :idSet];
        Test.startTest();
        Set<Id> epId = SessionTriggerHandler.getIdOfLastModifiedPlaces(s);
        Test.stopTest();
        for (Session__c ses: s) {
            for (Id ep : epId) {
                Assert.areEqual(ses.Room__r.Event_Place__r.Id, ep, 'Id mismatch');  
            }
        }
    }

    @isTest
    private static void testIsDateChangedNegative(){
        List<Session__c> s = TestDataFactory.getNewSession(1);
        Test.startTest();
        Boolean subjectResult = SessionTriggerHandler.isDateChanged(s, s);
        Test.stopTest();
        Assert.areEqual(false, subjectResult, 'No date modification expected');
    }

    @isTest
    private static void testIsDateChangedPositive(){
        List<Session__c> s = TestDataFactory.getNewSession(1);
        List<Session__c> s2 = TestDataFactory.getNewSession(1);
        s2[0].Session_Date__c = Datetime.now();
        Test.startTest();
        Boolean subjectResult = SessionTriggerHandler.isDateChanged(s, s2);
        Test.stopTest();
        Assert.areEqual(true, subjectResult, 'Date modification expected');
    }

    @isTest
    private static void testEnqueueJobOnDateUpdate(){
        List<Session__c> s = TestDataFactory.getNewSession(1);
        insert s;
        List<Session__c> s2 = [SELECT Id, Session_Date__c FROM Session__c WHERE Id IN :s];
        s2[0].Session_Date__c = Datetime.now();
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestDataFactory());
        update s2;
        Test.stopTest();

        String resJSON = '[ { "userId": 1, "id": 1, "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit", "body": "quia et suscipit\\nsuscipit recusandae consequuntur expedita et cum\\nreprehenderit molestiae ut ut quas totam\\nnostrum rerum est autem sunt rem eveniet architecto" }, { "userId": 1, "id": 2, "title": "qui est esse", "body": "est rerum tempore vitae\\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\\nqui aperiam non debitis possimus qui neque nisi nulla" }]';
        List<JSONPlaceHolder> eoExpected = (List<JSONPlaceHolder>) JSON.deserialize(resJSON, List<JSONPlaceHolder>.class);
        List<ExternalObject__c> eoActual = [SELECT id__c, title__c FROM ExternalObject__c WHERE id__c = '1'];
        Assert.areEqual(eoExpected[0].title, eoActual[0].title__c, 'Expected object missing');
    }
}