force-app/main/default/objects/Event_Place__c/Event_Place__c.object-meta.xml
<CustomObject>
    <label>Event Place</label>
    <nameField>
        <label>Event Place Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Place__c/fields/Number_of_related_sessions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_related_sessions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of related sessions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Place__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Event_Place__c.field-meta.xml
<CustomField>
    <fullName>Event_Place__c</fullName>
    <label>Event Place</label>
    <referenceTo>Event_Place__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event_Place_counter_switch__c.field-meta.xml
<CustomField>
    <fullName>Event_Place_counter_switch__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Event Place counter switch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>Speaker-{0}</displayFormat>
        <label>Session Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Room</relationshipLabel>
    <relationshipName>Room</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionNumScheduledBatch.cls
public with sharing class SessionNumScheduledBatch implements Database.Batchable<SObject>, Schedulable {
    
    String query = 'SELECT Id, Number_of_related_sessions__c FROM Event_Place__c';
    
    public SessionNumScheduledBatch() {

    }

    public static void fireOncePerDaySchedule(){
        String cronExp = '0 0 0 ? * * *';
        System.schedule('DailySessionNumUpdate', cronExp, new SessionNumScheduledBatch());
    }

    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new SessionNumScheduledBatch(), 200);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Event_Place__c> scope){
        List<AggregateResult> newValuesList = [SELECT Room__r.Event_Place__r.Id, 
                                          COUNT(Id) counter 
                                          FROM Session__c
                                          WHERE Session__c.Event_Place_counter_switch__c = true
                                          GROUP BY Room__r.Event_Place__r.Id];

        Map<Id,Decimal> newValuesMap = new Map<Id,Decimal>();
            for (AggregateResult agr : newValuesList) {
              newValuesMap.put((Id)agr.get('Id'), (Decimal)agr.get('counter'));
                }
        
        Map<Id,Decimal> oldValues = new Map<Id,Decimal>();
            for (Event_Place__c p : scope) {
                oldValues.put(p.Id, p.Number_of_related_sessions__c);
                }          

        List<Event_Place__c> updateable = new List<Event_Place__c>();
        Set<Id> setone = oldValues.keySet();        
        for (Id key : setone) {
            if(oldValues.get(key) != newValuesMap.get(key)){
                updateable.add(new Event_Place__c (Id = key,  
                                                   Number_of_related_sessions__c = newValuesMap.get(key)));
            }
        }
        if(!updateable.isEmpty()){
            update updateable;
        }
    }
    public void finish(Database.BatchableContext bc){
    
    }

}