force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/postId__c.field-meta.xml
<CustomField>
    <fullName>postId__c</fullName>
    <label>postId</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalCommentsHandler.cls
public with sharing class ExternalCommentsHandler implements Queueable, Database.AllowsCallouts {
    public ExternalCommentsHandler() {

    }

    public void execute(QueueableContext context) {
        //GET + deserialize
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        
        request.setEndpoint('callout:Legacy/comments');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        
        if(response.getStatusCode() == 200) {    
            List<Comment> results = (List<Comment>) System.JSON.deserialize(response.getBody(), List<Comment>.class);
            
            List<Comment__c> extObjects = new List<Comment__c>();

            for (Comment c : results) {
                extObjects.add(new Comment__c(postid__c = c.postId,
                                              id__c = c.id,
                                              name__c = c.name,
                                              email__c = c.email,
                                              body__c = c.body));
            }
        insert extObjects;
        }
    }


    public class Comment{
        public String postId;
        public String id;
        public String name;
        public String email;
        public String body;
    }
}