force-app/main/default/objects/ExternalObject__c/ExternalObject__c.object-meta.xml
<CustomObject>
    <label>ExternalObject</label>
    <nameField>
        <label>ExternalObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExternalObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalObject__c/fields/body__c.field-meta.xml
<CustomField>
    <fullName>body__c</fullName>
    <label>body</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExternalObject__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExternalObject__c/fields/userId__c.field-meta.xml
<CustomField>
    <fullName>userId__c</fullName>
    <label>userId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalObjectsHandler.cls
public with sharing class ExternalObjectsHandler implements Queueable, Database.AllowsCallouts {
    public ExternalObjectsHandler() {

    }

    public void execute(QueueableContext context) {
        //GET + deserialize
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        
        request.setEndpoint('https://jsonplaceholder.typicode.com/posts');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        
        if(response.getStatusCode() == 200) {    
            List<JSONPlaceHolder> results = JSONPlaceHolder.parse(response.getBody());
            List<ExternalObject__c> extObjects = new List<ExternalObject__c>();

            for (JSONPlaceHolder j : results) {
                extObjects.add(new ExternalObject__c(body__c = j.body,
                                                     id__c = j.id,
                                                     title__c = j.title,
                                                     userId__c = j.userId));
            }
        insert extObjects;
        System.enqueueJob(new ExternalObjectHandlerPOST());
        }
    }

    public static void cleanBeforeQueue(){
        List<ExternalObject__c> objectsToDelete = [SELECT id FROM ExternalObject__c];
        if (!objectsToDelete.isEmpty()) {
            delete objectsToDelete;
        }
    }

}