force-app/main/default/objects/ExternalObject__c/ExternalObject__c.object-meta.xml
<CustomObject>
    <label>ExternalObject</label>
    <nameField>
        <label>ExternalObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExternalObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalObject__c/fields/body__c.field-meta.xml
<CustomField>
    <fullName>body__c</fullName>
    <label>body</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExternalObject__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExternalObject__c/fields/userId__c.field-meta.xml
<CustomField>
    <fullName>userId__c</fullName>
    <label>userId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalObjectHandlerPOST.cls
public with sharing class ExternalObjectHandlerPOST implements Queueable, Database.AllowsCallouts {
    public ExternalObjectHandlerPOST() {

    }
    public void execute(QueueableContext context) {
        //POST + serialize
        Http http2 = new Http();
        HttpRequest request2 = new HttpRequest();

        request2.setEndpoint('https://jsonplaceholder.typicode.com/posts');
        request2.setMethod('POST');

        List<ExternalObject__c> objectsToPOST = [SELECT body__c, id__c, title__c, userId__c
                                                 FROM ExternalObject__c
                                                 WHERE id__c = '1'];       
        List<String> jsonToPostList = new List<String>();
        for (ExternalObject__c e : objectsToPOST) {
            jsonToPostList.add(JSON.serialize(e));
        }

        for (String j : jsonToPostList) {
            request2.setBody(j);
            HttpResponse responseOnPOST = http2.send(request2);

            if(responseOnPOST.getStatusCode() != 201) {
                System.debug('The status code returned was not expected: ' + responseOnPOST.getStatusCode() + ' ' + responseOnPOST.getStatus());
            } else {
                System.debug(responseOnPOST.getBody());
            }
        }
    }
}