force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddSessionController.cls
public class AddSessionController {

    @AuraEnabled
    public static Response addNewSession(String sessionName, String sessionDateTime){
        Response resp;
        Datetime dt = (DateTime)JSON.deserialize('"' + sessionDateTime + '"', DateTime.class);

        try {
            Session__c s = new Session__c(Name = sessionName, 
                                          Session_Date__c = dt,
                                          Room__c = Id.valueOf('a067Q000007EphuQAC'));
            resp = new Response(s);
            insert s;
        } catch (Exception e) {
            resp = new Response(e);
        }
        return resp;
    }
    
}