force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Days_remains__c.field-meta.xml
<CustomField>
    <fullName>Days_remains__c</fullName>
    <formula>Session_Date__c  - DATETIMEVALUE(TODAY())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days remains</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionRestService.cls
@RestResource (urlMapping='/sessionsrestservice/*')
global class SessionRestService {
    public SessionRestService() {

    }
    //workbench: /services/apexrest/sessionsrestservice
    @HttpGet
    global static void getSessionsOnWeek() {
        List<Session__c> s = [SELECT Id, Name 
                              FROM Session__c 
                              WHERE Days_remains__c >= 0 
                              AND Days_remains__c <= 7
                              FOR UPDATE];

        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(s));
        RestContext.response.statusCode = 200;
    }


    //workbench: /services/apexrest/sessionsrestservice?id=a097Q0000033II5QAM (use id from the get method)
    @httpDelete
    global static void deleteSession(){
        Map<String,String> paramsMap = RestContext.request.params;
        String sessionId = paramsMap.get('id');
        Session__c s = [SELECT id FROM Session__c WHERE Id =:sessionId FOR UPDATE];
        delete s;
    }

    //workbench: /services/apexrest/sessionsrestservice 
    //JSON sample:
    //{
    //    "Name": "restsession",
    //    "Room__c": "a067Q000007EphuQAC"   
    //}
    @httpPost
    global static void createSession(){
        Session__c sessionToInsert = (Session__c) JSON.deserialize(RestContext.request.requestBody.toString(), Session__c.class);
        insert sessionToInsert;       
    }

    //workbench: /services/apexrest/sessionsrestservice 
    //JSON sample (use id from get method):
    //{      
    //    "id": "a097Q0000031qPmQAI",
    //    "Description__c": "the most incredible session forever"
    //}
    @httpPatch
    global static void editSessionDescription(){
        Session__c sessionUpdate = (Session__c) JSON.deserialize(RestContext.request.requestBody.toString(), Session__c.class);
        update sessionUpdate;
    }
}